#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Prevent running lint-staged inside the continuous integration container
if [ -z  "$CI" ] && [ -z "$CONTINUOUS_INTEGRATION" ]; then
	pnpm lint-staged --verbose
fi
